- !!python/object:operation.Operation {date: !!timestamp '2017-05-18 00:00:00', description: donate_with_yaml,
  money: 123}
- !!python/object:operation.Operation {date: !!timestamp '2017-05-20 00:00:00', description: donate,
  money: 100}
- !!python/object:operation.Operation {date: !!timestamp '2017-05-20 00:00:00', description: another_donate,
  money: -111}
- !!python/object:operation.Operation {date: !!timestamp '2017-05-20 00:00:00', description: one_more_donate,
  money: 222}
- !!python/object:operation.Operation {date: !!timestamp '2017-06-01 00:00:00', description: qwerty_donate,
  money: 222}
- !!python/object:operation.Operation {date: !!timestamp '2017-06-02 00:00:00', description: general_donate,
  money: -222}
- !!python/object:operation.Operation {date: !!timestamp '2917-06-04 00:00:00', description: 'donate ',
  money: 1111}
- !!python/object:operation.Operation {date: !!timestamp '2017-06-04 00:00:00', description: yaml_donate,
  money: 123}
- !!python/object:operation.Operation {date: !!timestamp '2017-06-04 00:00:00', description: test_donate,
  money: -123}
- !!python/object:operation.Operation {date: !!timestamp '2017-06-04 00:00:00', description: donate,
  money: 100}
